name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: TilBlechschmidt/gp-docker-action@v0.2-alpha
        with: 
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: "focusBot"
          image-tag: "latest"
